LEVEL1_BACKGROUND = "data/background.jpg"
LEVEL2_BACKGROUND = "data/warcraft_data/background.jpg"

HP_FRAME = "data/hpframe.png"
MP_FRAME = "data/mpframe.png"

HP_TICK = "data/hptick.png"
MP_TICK = "data/mptick.png"

PLAYER_RIGHT = "data/right.png"
PLAYER_DOWN = "data/down.png"
PLAYER_LEFT = "data/left.png"
PLAYER_UP = "data/up.png"

DEMON_RIGHT = "data/demonr.png"
DEMON_DOWN = "data/demond.png"
DEMON_LEFT = "data/demonl.png"
DEMON_UP = "data/demonu.png"

ARROW = "data/arrow.png"
FIREBALL = "data/fireball_fly.png"
BARRIER = "data/enviroment_textures/infinity_barrier.jpg"
HUD_HP = "data/hud_hp.png"
HUD_MANA = "data/hud_mana.png"
HUD_HP_TICK = "data/hud_hp_tick.png"
HUD_MANA_TICK = "data/hud_mana_tick.png"
HUD_FRAME = "data/hud_frame.png"
PERK_ARROW = "data/range_aa.png"
PERK_FIREBALL = "data/fireball.bmp"
HUD_FRAME_CHOSEN = "data/hud_frame_chosed.png"
HP_POTION = "data/Hp_potion.png"
MP_POTION = "data/Mp_potion.png"
CUTTED_TREE = "data/cutted_tree.png"
TREE = "data/bush.png"
CASTLE_BACKGROUND = "data/Castle_background.jpg"
COLUMN = "data/Column.png"
CHEST = "data/Chest.png"
TORCH = "data/Torch.png"
GRASS = "data/grass.png"
GRID = "data/grid.png"
